### ISSUE TITLE
Not working with VS Mac version 8.4.2 (build 59)

### ISSUE THREAD

**Issue by baskren** [mrward/monodevelop-nuget-package-explorer#5]
First, please accept my apologies if I am at the wrong place.  

Second, if I am at the right place, I really want to let you know just how much easier your package makes my life as a developer!  THANK YOU.

Also, if there is anything I can do to help you fix this, please let me know.  This tool is just too useful to me!

## Description

NuGet Package Explorer (for VS Mac) seems to break with most VS Mac updates.

## Observed Behavior

Below is how this issue manifested itself after the most recent VS Mac update:

1. Have working install of NuGet Package Manager in VS Mac.  
2. Upgrade VS Mac to latest stable release, 8.4.2 (build 59).  
3. I'm a little foggy on this one.  Either:
    - NuGet Package Explorer will be disabled on VS Mac restart
    - Reinstalling or Reenabling NuGet Package Explorer will show the below error message after another VS Mac restart
**_or_**
    - NuGet Package Explorer will show the below error message on VS Mac Restart

<img width="2116" alt="image" src="https://user-images.githubusercontent.com/2528888/73356178-bc832f00-4267-11ea-9c9a-2ba9c7b42384.png">

*My apologies: there doesn't appear to be a way to copy the text from the above dialog!*

4. The above message will not be shown if  NuGet Package Explorer is disabled and VS Mac is restarted.

## Desired Behavior

NuGet Package Explorer continues to work after VS Mac updates

### NuGet Package Explorer

version 0.3.1

### VS Mac

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.4.2 (build 59)
Installation UUID: 26005b3b-9138-4f2c-bfe5-49f194d72001
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
SDK Versions:
	3.1.101
	3.1.100
	3.0.101
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.1
	3.1.0
	3.0.1
	2.1.15
	2.1.14

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Enterprise)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/benjaminaskren/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/benjaminaskren/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:04 UTC

=== Android Device Manager ===

Version: 16.4.0.30
Hash: f9172e2
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Version: 6.10.0.17 (Visual Studio Enterprise)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Enterprise)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin Designer ===

Version: 16.4.0.478
Hash: 95f0ab363
Branch: remotes/origin/d16-4
Build date: 2020-01-08 23:59:46 UTC

=== Build Information ===

Release ID: 804020059
Git revision: eb6fcdd83a227678e487aa733df3c8745f54fafc
Build date: 2020-01-17 12:12:02+00
Build branch: release-8.4
Xamarin extensions: ec32c90978c94f03d72f507b01f5aee70952ce87

=== Operating System ===

Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
NuGet Package Explorer 0.3.1
NuGet Package Management Extensions 0.21
Open With 0.2
MSBuild Editor 2.2.0

**Comment by mrward** [comment]
If you install NuGet Package Explorer 0.4 then that should work in VS Mac 8.3 and above. You can download it directly from here:

http://addins.monodevelop.com/Project/Index/242

I will re-publish 0.4 for VS Mac 8.4.2 to the main addin server. The addin server does not seem to auto-publish addins when you publish it for older versions.

**Comment by mrward** [comment]
Republished NuGet Package explorer 0.4 for VS Mac 8.4.2 and 8.4.3.

**Comment by baskren** [comment]
Thanks, Matt!  It works great.  Again, greatly appreciate that you're keeping this package alive - it is a great tool.

**Comment by mrward** [comment]
Thank you for using it. I use it myself pretty much every day and it is good that it is useful for other people too 😄
